chacra/models/__init__.py, chacra/models/binaries.py, chacra/models/repos.py, chacra/tests/models/test_binaries.py, chacra/tests/models/test_repos.py
Implements the model for Repos, adding tests too.
Moves the listener for modified timestamps to a generic spot.
=> Repos model

README.rst
=> Update how combined repos are defined in the README

chacra/hooks.py, deploy/playbooks/roles/common/templates/prod.py.j2
Signed-off-by: Alfredo Deza <alfredo@deza.pe>
=> create a hook to catch exceptions on prod environments

deploy/playbooks/roles/common/tasks/nginx.yml, deploy/playbooks/roles/common/vars/main.yml
And remove mongodb, not sure how I managed to copy/pasta'd there
=> ensure an nginx user exists

chacra/controllers/root.py
=> fix the root controller to show /binaries instead of /projects

deploy/playbooks/roles/common/tasks/main.yml
=> ensure paths are set with proper ownership and permissions

deploy/playbooks/roles/common/templates/circus.ini.j2
=> Put the celery logs into /var/log/circus

chacra/async/__init__.py, chacra/tests/test_util.py, chacra/util.py
With tests and some docs. They are pretty simple but allows us to have leaner tasks with reusable code.
=> create a few utitlities for the celery tasks

chacra/async/__init__.py, config/dev.py, deploy/playbooks/roles/common/tasks/nginx.yml, deploy/playbooks/roles/common/templates/prod.py.j2
Fixes a few issues with deployment as well that would prevent celery from working correctly.
=> Configurable `quiet_time` and `polling` for Celery tasks

chacra/controllers/binaries/__init__.py, deploy/playbooks/roles/common/templates/nginx_site.conf
I swear this works. But we should think about making the swap on the path configurable.
=> Nginx downloads

deploy/playbooks/roles/common/handlers/main.yml, deploy/playbooks/roles/common/tasks/postgresql.yml
=> restart celery when we change the db password

chacra/commands/populate.py, deploy/playbooks/roles/common/handlers/main.yml, deploy/playbooks/roles/common/tasks/main.yml, deploy/playbooks/roles/common/tasks/postgresql.yml, deploy/playbooks/roles/common/templates/circus.ini.j2
Starts the celery beat process as recommended for production usage.
Creates a prod alembic.ini file for use with the populate command.
=> celery beat and alembic ansible

README.rst
=> update README to replace /projects with /binaries

deploy/playbooks/roles/common/templates/prod_db.py.j2
=> do not log sqlalchemy queries in production

chacra/controllers/repos/__init__.py, chacra/tests/controllers/repos/test_repos.py
Mostly relies on Celery except for the `rmtree` by shutil. Added tests.
=> allow CRUD operations on repositories

chacra/async/__init__.py
=> get all the binaries from the actual parent repo for rpms

chacra/controllers/repos/__init__.py, chacra/tests/conftest.py, chacra/tests/controllers/repos/test_repos.py
So that we can use it in chacractl to check for existence of repos
=> Allow head requests on repos

chacra/async/__init__.py, chacra/models/binaries.py, chacra/tests/models/test_binaries.py, chacra/tests/test_util.py, chacra/util.py
This will alow us to include dsc and changes files in deb repos.
Adds tests.
This is now good to merge!
=> async support for both .changes and .dsc files

deploy/playbooks/roles/repos/defaults/main.yml
=> add all the known current and future debian codenames possible

chacra/controllers/binaries/archs.py, chacra/tests/controllers/test_binaries.py
=> return a 404 if there no binaries for an arch

chacra/controllers/binaries/refs.py, chacra/tests/controllers/test_refs.py
=> fix ref distros by improving the filtering

chacra/controllers/binaries/distros.py, chacra/tests/controllers/test_distros.py
Similar to the previous issue for refs.
=> better filter distro versions

README.rst
@alfredodeza 
@ktdreyer 
Signed-off-by: Gregory Meno <gmeno@redhat.com>
=> add https:// to curl example

deploy/playbooks/roles/common/tasks/main.yml
=> really really make sure nginx is up and running

deploy/playbooks/deploy_vagrant.yml, deploy/playbooks/roles/common/tasks/nginx.yml
=> enable ssl for development 

deploy/playbooks/roles/common/templates/prod.py.j2
=> add ceph-release to infernalis repo when it is built

deploy/playbooks/roles/common/templates/prod.py.j2
=> add jewel-rc binaries to testing

chacra/controllers/repos/distros.py, chacra/tests/controllers/repos/test_distros.py
=> fix bug showing versions for other refs at repos/project/ref/distro

deploy/playbooks/roles/common/templates/prod.py.j2
=> poll every two minutes, further preventing pile ups

chacra/async/__init__.py
=> fetch generic binaries that might exist for the same distro

chacra/models/binaries.py, chacra/models/repos.py, chacra/tests/models/test_binaries.py, chacra/tests/models/test_repos.py
Prevents universal/generic repositories from getting created.
=> No universal repos

chacra/async/__init__.py
=> no need to show the Popen traceback

README.rst, chacra/async/__init__.py, chacra/tests/test_util.py, chacra/util.py
So that @ktdreyer can trim his gigantic configuration dictionaries.
Adds tests and updates the docs as well.
=> Disable repos

chacra/controllers/projects.py, chacra/tests/conftest.py, chacra/tests/controllers/test_projects.py, chacra/tests/test_util.py
with a POST request.
It also fixes some environmental pollution from altering the app's configuration
=> allow to create a project

chacra/models/binaries.py, chacra/tests/controllers/test_binaries.py
So that @ktdreyer is like https://media.giphy.com/media/bqrG9EUt9vS4U/giphy.gif
=> include the project name in the json output

deploy/playbooks/roles/common/templates/prod.py.j2
=> add jewel so that it has ceph-release

deploy/playbooks/roles/common/handlers/main.yml
=> restart all of the celery workers

chacra/controllers/repos/__init__.py
=> set is_updating to False when updating or recreating a repo

chacra/constants.py
=> add xenial for reprepro configurations

deploy/playbooks/roles/common/templates/prod.py.j2
=> combine xenial binaries as well when available

chacra/async/__init__.py, chacra/tests/test_util.py, chacra/util.py
Already running and creating correctly the repos in prod.
=> `aarch64` support

chacra/models/repos.py, chacra/tests/controllers/repos/test_repos.py
It was missing a couple of fields
=> include extra metadata from repos

chacra/constants.py, chacra/controllers/binaries/archs.py, chacra/controllers/util.py, chacra/models/binaries.py, chacra/tests/controllers/test_binaries.py, chacra/util.py
=> allow disabling of automatic repositories

chacra/models/repos.py
=> include is_queued in the json response

deploy/playbooks/roles/celery/tasks/main.yml
=> enable web management for rabbitmq

README.rst
=> update the docs to correct the automatic behavior

deploy/playbooks/roles/common/tasks/systemd.yml
=> ansible: make sure that all services are running when deploying

deploy/playbooks/roles/common/handlers/main.yml
=> ansible: restart the app, celery, and celerybeat when config changes

deploy/playbooks/roles/common/templates/systemd/chacra.service.j2
=> ansible: bump the timeout to 20 minutes in gunicorn

deploy/playbooks/roles/common/handlers/main.yml, deploy/playbooks/roles/common/tasks/main.yml
=> explicitly restart celery and celerybeat on every deploy

chacra/controllers/binaries/__init__.py
Fixes: https://github.com/ceph/chacra/issues/124
=> updating binaries should use PUT not POST

chacra/controllers/binaries/__init__.py
=> Revert "updating binaries should use PUT not POST"

requirements.txt
=> use the correct statsd library

chacra/async/__init__.py, chacra/metrics.py, chacra/models/repos.py, chacra/tests/config.py, chacra/tests/test_metrics.py, setup.py
This will start firing up metrics when processing repos: counts how many binaries are being processed per repo and times collection of binaries and processing.
=> Fire metrics

chacra/controllers/binaries/__init__.py, chacra/controllers/projects.py, chacra/controllers/repos/distros.py, chacra/controllers/repos/projects.py, chacra/controllers/repos/refs.py, chacra/tests/config.py, chacra/tests/conftest.py, chacra/tests/controllers/repos/test_projects.py, chacra/tests/controllers/test_search.py, chacra/tests/models/test_binaries.py, chacra/tests/models/test_repos.py, chacra/tests/test_util.py, tox.ini
flake8 tests will now run on each PR with this change
=> fixes flake8 errors and adds flake8 to the tox envlist

deploy/playbooks/roles/statsd/templates/config/localConfig.js.j2
=> fix syntax error in statsd configuration

chacra/controllers/repos/__init__.py, chacra/tests/controllers/repos/test_repos.py
=> Force requeue

chacra/async/__init__.py, chacra/async/base.py, chacra/async/debian.py, chacra/async/recurring.py, chacra/async/rpm.py
modularize all celery tasks into their own modules, making it easier for other code to be added later and make files smaller
fixes #146
=> Async cleanup

deploy/playbooks/deploy.yml, deploy/playbooks/deploy_vagrant.yml
=> use the celery role before so that rabbit can be installed

deploy/playbooks/deploy.yml, deploy/playbooks/deploy_vagrant.yml, deploy/playbooks/roles/common/defaults/main.yml, deploy/playbooks/roles/common/tasks/main.yml, deploy/playbooks/roles/common/templates/hosts.j2
=> Fix host file mangling

chacra/async/__init__.py, chacra/async/debian.py, chacra/async/recurring.py, chacra/async/rpm.py, chacra/controllers/repos/__init__.py, chacra/models/repos.py, chacra/tests/config.py, deploy/playbooks/deploy.yml, deploy/playbooks/deploy_vagrant.yml, deploy/playbooks/roles/common/tasks/main.yml, deploy/playbooks/roles/common/templates/prod.py.j2, deploy/playbooks/roles/common/templates/prod_callbacks.py.j2, requirements.txt, setup.py
=> implement callbacks

chacra/app.py, chacra/async/__init__.py, chacra/async/checks.py, chacra/async/recurring.py, chacra/tests/async/test_checks.py, deploy/playbooks/ansible.cfg, deploy/playbooks/deploy_vagrant.yml, deploy/playbooks/roles/common/tasks/main.yml, deploy/playbooks/roles/common/templates/prod.py.j2, deploy/playbooks/roles/common/templates/prod_callbacks.py.j2
Implements callback feature to ping shaman on startup.
=> health pings

deploy/playbooks/deploy.yml, deploy/playbooks/roles/common/templates/prod_callbacks.py.j2
Unless explicitly asked for when deploying.
=> Default to no health pings

chacra/async/__init__.py, chacra/tests/conftest.py
This will actually make celery beat work again in prod.
=> configure celery beat at module level

deploy/playbooks/examples/deploy_test.yml
=> adds api_key and api_user placeholders to examples/deploy_test.yml

chacra/controllers/binaries/archs.py, chacra/controllers/binaries/flavors.py, chacra/models/binaries.py, chacra/models/repos.py, chacra/tests/test_util.py, chacra/util.py
These were not being set.
Also fixed a few inconsistencies, mainly with sha1 and flavor flav not being set when constructing the object.
=> Repo path fixes

deploy/playbooks/roles/common/vars/main.yml
=> add letsencrypt to the ssl_requirements list

README.rst
=> update README to include sha1 in the example urls

deploy/playbooks/examples/deploy_prod.yml
=> ansible: turn off letsencrypt for prod playbook

deploy/playbooks/roles/common/tasks/letsencrypt.yml
=> ansible: use letsencrypt renew vs. asking for a new cert every 12 hours

chacra/tests/test_util.py, chacra/util.py
Use flavor flav paths everywhere
=> Flavor repo paths

chacra/async/__init__.py, chacra/models/repos.py, chacra/tests/async/test_callbacks.py
Shaman needs these passed on. 
Adds some tests to validate the fields and values.
=> Repo json fields

chacra/async/recurring.py
=> async: make requests raise for non-200 repsonses

chacra/async/__init__.py, chacra/async/recurring.py, chacra/tests/async/test_callbacks.py, chacra/tests/async/test_recurring.py, chacra/tests/controllers/test_distros.py, deploy/playbooks/examples/deploy_test.yml, deploy/playbooks/roles/common/templates/prod.py.j2
=> Auto remove/purge old repos and binaries

chacra/models/repos.py, chacra/tests/controllers/repos/test_repos.py, chacra/tests/models/test_repos.py
It will look at binaries and will return a list of all the binaries archs.
=> `repo.archs` support

chacra/controllers/repos/__init__.py, chacra/models/repos.py, chacra/models/types.py, chacra/tests/controllers/repos/test_repos.py
Support for `extra/` to extend repository metadata from a build.
=> extra endpoint

chacra/async/recurring.py
=> async: commit when purging repos

deploy/playbooks/examples/deploy_test.yml, deploy/playbooks/roles/common/templates/prod.py.j2
This fixes https://github.com/ceph/chacra/issues/196
=> Do not combine deb repos on test chacra nodes

chacra/async/recurring.py, chacra/tests/async/test_recurring.py
=> remove repo paths when purging repos

chacra/async/checks.py, chacra/tests/async/test_checks.py
So that we can behave better when almost full (used an `85%` rule there)
=> Disk health check

chacra/controllers/util.py, chacra/models/repos.py, chacra/util.py
Checked Python codes by using flake8.
Changed % string format into .format for better readibility.
=> Code cleanup by using .format

chacra/templates/repo.mako
=> adds [trusted=yes] to generated debian source file

deploy/playbooks/roles/common/templates/prod.py.j2
=> ansible: fix syntax error, missing trailing comma in dict

chacra/controllers/binaries/__init__.py, chacra/controllers/binaries/flavors.py, chacra/tests/controllers/test_binaries.py, chacra/tests/controllers/test_flavors.py
Adds a couple of tests (one for each issue).
=> improve flavor queries and prevent binaries from different archs to show up

deploy/playbooks/roles/common/templates/prod.py.j2
=> deploy: add debian stretch to combined repos

deploy/playbooks/roles/common/templates/prod.py.j2
=> deploy: remove radosgw-agent from being added on ceph repos

deploy/playbooks/roles/common/templates/prod.py.j2
=> deploy: add ceph-medic to ceph repos

deploy/playbooks/roles/common/tasks/main.yml
=> deploy: use quoted variables for with_items

deploy/playbooks/roles/common/tasks/letsencrypt.yml
=> ansible: Disable certbot's automatic renewal cron and daemons

chacra/hooks.py
=> hooks: don't log 404s and others as exceptions

deploy/playbooks/examples/deploy_test.yml, deploy/playbooks/roles/common/tasks/main.yml
Fixes: http://tracker.ceph.com/issues/19316
=> deploy: fix hostname dance

deploy/playbooks/roles/common/templates/prod.py.j2
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
=> deploy: preserve kernel/ceph-iscsi-stable builds

deploy/playbooks/roles/common/templates/prod.py.j2
=> deploy: Add luminous and mimic definitions

deploy/playbooks/roles/common/tasks/main.yml
Ensures the desired package/dependency versions are installed on
re-deployments
=> deploy: Force reinstall chacra

deploy/playbooks/roles/common/tasks/main.yml
=> deploy: Remove unattended-upgrades using sudo

chacra/constants.py, deploy/playbooks/roles/common/templates/prod.py.j2
=> Add support for Ubuntu Bionic 18.04

chacra/async/recurring.py, chacra/tests/async/test_recurring.py, deploy/playbooks/roles/common/templates/prod.py.j2
Signed-off-by: Ali Maredia <amaredia@redhat.com>
=>  nfs-ganesha: update purge rotation to keep nfs-ganesha binaries

chacra/async/debian.py
=> async handle Popen output when calling reprepro

deploy/playbooks/roles/common/templates/prod.py.j2
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
=> deploy: preserve ceph-iscsi/master builds

chacra/async/recurring.py, chacra/auth.py, chacra/commands/populate.py, chacra/compat.py, chacra/controllers/repos/__init__.py, chacra/models/__init__.py, chacra/models/binaries.py, chacra/models/types.py, chacra/templates/distributions, chacra/tests/async/test_recurring.py, chacra/tests/conftest.py, chacra/tests/controllers/repos/test_repos.py, chacra/tests/controllers/test_archs.py, chacra/tests/controllers/test_binaries.py, chacra/tests/controllers/test_flavors.py, chacra/tests/controllers/test_refs.py, chacra/tests/controllers/test_sha1s.py, chacra/tests/util.py, chacra/util.py, chacra/wsgi.py, requirements.txt, setup.py, tox.ini
Also fixes the super silly CVEs that don't really affect the project but are reported by Github anyway.
Fixes https://github.com/ceph/chacra/issues/264
=> Python3 compatibility

deploy/playbooks/roles/common/templates/prod.py.j2
=> deploy: Add octopus configs fro ceph-release package

chacra/constants.py, deploy/playbooks/roles/common/templates/prod.py.j2, deploy/playbooks/roles/repos/defaults/main.yml
=> chacra: Add Buster support

chacra/constants.py, deploy/playbooks/roles/common/templates/prod.py.j2
=> Add Focal Fossa

chacra/controllers/repos/__init__.py
Signed-off-by: Kefu Chai <kchai@redhat.com>
=> controllers/repos: add DELETE support

deploy/playbooks/redeploy-all.yml
=> deploy: Playbook to redeploy all chacra nodes one at a time

chacra/controllers/repos/__init__.py
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> controllers/repo: remove binaries when a repo is removed

deploy/playbooks/roles/common/tasks/postgresql.yml
=> deploy: Write a .pgpass file so we can backup the db

deploy/playbooks/roles/common/vars/main.yml
=> deploy: Install lz4 for backups

deploy/playbooks/roles/common/tasks/rabbitmq.yml
=> deploy: rabbitmq repo path changed

deploy/playbooks/roles/common/templates/prod.py.j2
=> prod.py: Add pacific

chacra/constants.py, deploy/playbooks/roles/common/templates/prod.py.j2, deploy/playbooks/roles/repos/defaults/main.yml
=> Add Debian bullseye

deploy/playbooks/roles/common/templates/prod.py.j2
=> prod.py.j2: Keep 10 latest nautilus builds

deploy/playbooks/roles/common/tasks/main.yml, deploy/playbooks/roles/common/vars/main.yml
=> deploy: install python3-dev and use python3 for virtualenv

README.rst, chacra/tests/async/test_recurring.py, chacra/tests/controllers/repos/test_repos.py, chacra/tests/controllers/test_binaries.py, chacra/tests/controllers/test_distros.py, chacra/tests/controllers/test_projects.py, chacra/tests/controllers/test_refs.py, chacra/tests/controllers/test_sha1s.py, chacra/tests/models/test_binaries.py, chacra/tests/models/test_repos.py, chacra/tests/test_util.py, chacra/util.py, deploy/playbooks/examples/deploy_prod.yml, deploy/playbooks/examples/deploy_test.yml, deploy/playbooks/examples/deploy_vagrant.yml, deploy/playbooks/roles/common/templates/prod.py.j2, scripts/crawl_repos.sh
=> Inclusive language update

chacra/constants.py, deploy/playbooks/roles/common/templates/prod.py.j2
=> Add Ubuntu 22.04
