ceph/chacra

chacra/commands/populate.py

This is in relation to the issue @alfredodeza shared with me: http://fpaste.org/256509/39421143/
For the populate command, you're inadvertently calling `model.init_model` twice (which you don't need to do):
https://github.com/ceph/chacra/blob/master/chacra/commands/populate.py#L19
https://github.com/pecan/pecan/blob/master/pecan/core.py#L221
https://github.com/ceph/chacra/blob/master/chacra/app.py#L7
In versions of pecan (prior to 1.0.1) the ``setattr`` portion of this line was not actually having the desired effect:
https://github.com/ceph/chacra/blob/master/chacra/models/__init__.py#L72
...because of this bug, which was fixed in 1.0.1:
https://github.com/pecan/pecan/pull/4
So in pecan 1.0.1, where the bug is fixed, you're modifying ``conf.sqlalchemy`` to have an `engine` property, and …

Don't call init_model() twice.

---

README.rst
chacra/auth.py
chacra/controllers/binaries.py
chacra/tests/config.py
chacra/tests/conftest.py
chacra/tests/controllers/test_archs.py
chacra/tests/controllers/test_binaries.py
chacra/tests/util.py

Uses Basic HTTP Auth. Adds tests for it  (and fixes broken ones), and it updates the documentation so that it correctly explains what we expect.

Implement Authentication for binaries

---

deploy/playbooks/deploy.yml
deploy/playbooks/deploy_vagrant.yml
deploy/playbooks/roles/repos/defaults/main.yml
deploy/playbooks/roles/repos/tasks/main.yml
deploy/playbooks/roles/repos/templates/distributions

This role does not yet quite work with the common role as we have to target Ubuntu for repo creation because we want to build both rpm and deb repos on the same node.
A port of the common role to Ubuntu will be necessary.

Adds a new repos role that configures the node to build repos

---

deploy/playbooks/roles/repos/defaults/main.yml

Remove raring from reprepro_distros list in the repos role

---

deploy/playbooks/deploy.yml
deploy/playbooks/deploy_vagrant.yml
deploy/playbooks/roles/common/handlers/main.yml
deploy/playbooks/roles/common/tasks/circus.yml
deploy/playbooks/roles/common/tasks/main.yml
deploy/playbooks/roles/common/tasks/nginx.yml
deploy/playbooks/roles/common/tasks/postgresql.yml
deploy/playbooks/roles/common/templates/circus.conf
deploy/playbooks/roles/common/vars/main.yml

We needed to do this port because we want the cachra node to run
the api as well as do the repo creation work. Trusty is the only
distro, afaik, that supports the needed packages to do this.

Port the common role from centos 7 to ubuntu trusty

---

chacra/models/binaries.py
chacra/tests/models/test_binaries.py

With SqlAlchemy listeners.
Adds tests for binary model.

automatic `modified` timestamps

---

chacra/controllers/binaries.py
chacra/tests/controllers/test_binaries.py

So that a binary that gets posted with the same name is not flagged as "request is trying to modifying existing binary".
Endpoints make it unique.
Adds tests

More granular POST checks

---

chacra/models/repos.py
config/dev.py

Adds api_user an api_key to config/dev.py
Fixes ``chacra.models.repos.Repos.__repr__``

A couple small tweaks

---

chacra/controllers/repos/__init__.py
chacra/controllers/repos/distros.py
chacra/controllers/repos/projects.py
chacra/controllers/repos/refs.py
chacra/controllers/root.py
chacra/models/projects.py
chacra/models/repos.py
chacra/tests/controllers/repos/test_distros.py
chacra/tests/controllers/repos/test_projects.py
chacra/tests/controllers/repos/test_refs.py
chacra/tests/controllers/repos/test_repos.py

This still needs to be setup to have nginx serve the repo directory
after creation and for RepoApiController to allow modification and
deletion of repos.

Start of the /repos endpoint

---

chacra/controllers/repos/__init__.py
chacra/schemas/__init__.py
chacra/tests/controllers/repos/test_repos.py
setup.py

Updating the following fields are supported: distro, distro_version,
ref and needs_update.
This also includes validation of the endpoint using pecan-notario.

Adds POST functionality to /repos/project/ref/distro/distro_version/

---

chacra/controllers/repos/__init__.py
chacra/models/__init__.py
chacra/models/binaries.py
chacra/tests/controllers/repos/test_repos.py

This lets us use that method for both binaries and repos.
Also returns self.repo from the repo api endpoint after an update has been performed and adds a couple tests to verify that returned json is correct.

Refactor Binary.update_from_json into Base.update_from_json

---

deploy/playbooks/deploy.yml
deploy/playbooks/deploy_vagrant.yml
deploy/playbooks/roles/celery/tasks/main.yml
deploy/playbooks/roles/common/templates/circus.ini.j2
deploy/playbooks/roles/common/vars/main.yml
requirements.txt

The role installs celery and rabbitmq, but does not start the celery workers.  We should probably use supervisord for that, I'll send another PR for that work.

adds a new celery role

---

deploy/playbooks/roles/common/tasks/circus.yml
deploy/playbooks/roles/common/templates/circus.conf
deploy/playbooks/roles/common/templates/circus.ini.j2

We had to do this so that the celery workers would start. Before this
change circusd was running as root which made the celery workers try to
use root as well, which is not what we want.

run circusd as ansible_ssh_user

---

alembic.ini
alembic/README
alembic/env.py
alembic/script.py.mako
chacra/commands/populate.py
requirements.txt

This sets up the environment and stamps the initial database state in our populate command.
We do this so that revisions are only used to modify and update an out-of-date database. There is no need to define our entire schema in an "intial_db_state" revision of some sort, sqlalchemy does this better and we're already leveraging that in the populate command.

Setup alembic environment

---

deploy/playbooks/roles/common/templates/alembic-prod.ini.j2

I forgot to include the template for the prod alembic config in my last pull, oops. Also, we need to make sure the alembic/versions folder is present or alembic complains when we try to stamp the initial db state with the populate command.

alembic ansible tweaks

---

README.rst
chacra/async/__init__.py
chacra/models/binaries.py
chacra/tests/test_util.py
chacra/util.py
deploy/playbooks/roles/common/templates/prod.py.j2

Docs are lacking, but this PR was getting too big.
Addressed a couple of issues, like models.Repo not getting the `needs_update` flag when creating binaries on existing repos.

enable multi repo combination (mostly for DEBs)

---

deploy/playbooks/roles/common/templates/prod.py.j2

The disadvantage I see here is having to pass the api_key and api_user vars every time we deploy so we don't inadvertently reset prod to the defaults or something.
We might want to change this in the future so we don't need to do that.

api_key and api_user now use variables in the prod config

---

deploy/playbooks/roles/common/vars/main.yml
requirements.txt

because using the shell in prod without ipython or changing files around without vim is egregious

install vim and ipython

---

deploy/playbooks/roles/common/templates/nginx_site.conf

Add HTTPS to the chacra web server to protect authentication.
The key and certificate files are managed outside of Ansible.

ansible: nginx config for HTTPS

---

deploy/playbooks/roles/common/templates/nginx_site.conf

This will cause a browser to automatically load the "https://" URL when the user enters "chacra.ceph.com" into the browser.
Since we're not listening on port 80 any more, this change should make it a bit more user-friendly.
See https://www.owasp.org/index.php/HTTP_Strict_Transport_Security for more information

ansible: set HSTS header in nginx

---

chacra/tests/test_util.py
chacra/util.py

This fixes a bug where a distinct ref would be chosen vs using both 'all' and the distinct one.
This happens when for example Ceph infernalis needs all versions of ceph-deploy in but just the infernalis version of ceph-release.

find all refs and distinct ones

---

deploy/playbooks/roles/common/templates/prod.py.j2

This is to hopefully avoid a race condition where a .dsc file gets
uploaded before a .orig.tar.gz does and the repo fails to add the .dsc.

increase the prod polling_time and quiet_time

---

chacra/async/__init__.py
chacra/controllers/repos/__init__.py
chacra/tests/controllers/repos/test_repos.py

And prevent dog-pilling work on creating repos by marking the repo as `needs_update = False` before doing anything else

Safer recreate repo

---

deploy/playbooks/roles/common/templates/prod.py.j2

just include 'master' builds for ceph-deploy and radosgw-agent

---

chacra/tests/test_util.py
chacra/util.py

The use of `.first()` meant that if multiple repos where matched we would ignore them and use just the first one.
Adds a test to ensure the problem first and the fix later.

Fix an issue that prevented combined repos from working

---

deploy/playbooks/roles/common/templates/prod.py.j2

add universal as another 'distro version' to be used when combining binaries for ceph

---

deploy/playbooks/roles/common/templates/nginx_site.conf

Users will hit eg. "https://chacra.ceph.com/", not "https://localhost/". Set the `server_name` in our Nginx configuration to reflect this.

ansible: use fqdn for nginx server name

---

chacra/async/__init__.py
chacra/models/binaries.py
chacra/tests/test_util.py
chacra/util.py
deploy/playbooks/roles/common/templates/prod.py.j2

This is very well documented in the docstrings, but mainly we are now generating a bunch of `reprepro` commands because a generic binary might need to be 'added' to different distro version combinations

generic binary support for reprepro commands

---

README.rst
chacra/controllers/search.py
chacra/tests/controllers/test_search.py

because it will allow to use `name-like=ceph` and get proper results. Otherwise users are forced to have the exact name they are looking for
Fixes issue #80

Better search

---

chacra/async/__init__.py

Although we had support for generic DEB binaries, we were not looking for generic binaries for projects that were configured as 'extras'. 
In this case, this means that when building a repository for 'ceph' the generic binaries from 'ceph-deploy' where not being added. This PR fixes this.

add generic binaries from the extra repos as well

---

chacra/async/__init__.py
deploy/playbooks/roles/common/templates/prod.py.j2

This was causing that generic binaries wouldn't be included in jessie repos.
It also adds a `set()` call to ensure we are not overloading reprepro for no good reason.

include jessie when combining repos

---

chacra/async/__init__.py
chacra/controllers/binaries/archs.py
chacra/models/projects.py
chacra/tests/controllers/test_binaries.py
chacra/tests/test_util.py
chacra/util.py

This PR addresses the issue of POSTing a new binary and not triggering a repository build (or update) for a related project.
For example if a ceph-deploy binary, that is configured to get included in the ceph project repos is POSTed, chacra will now understand that a relationship exists and will mark the corresponding repositories for the ceph project to get updated.
If configuration exists for a new project that hasn't been created yet, this PR will address the problem of creating that project and the repository model objects as well.

mark related repositories for update

---

chacra/async/__init__.py
chacra/controllers/binaries/archs.py
chacra/models/binaries.py
chacra/models/repos.py
chacra/tests/controllers/test_binaries.py
chacra/tests/models/test_repos.py

There are situations where *related* repos that are created because of a configured relationship might not have the type set.
This PR fixes this so that at creation time if the Repo does not exist the type will be set.

infer repo type

---

deploy/playbooks/roles/common/templates/circus.ini.j2
deploy/playbooks/roles/common/templates/nginx_site.conf

This bumps the timeouts for both nginx and gunicorn, it also bumps the max size allowed to 2GB, and finally it adds 3 more workers to celery.

Fix timeouts (thanks to ceph-debuginfo)

---

chacra/controllers/binaries/archs.py
chacra/controllers/binaries/distros.py
chacra/tests/controllers/test_distros.py

By relying on database queries with as much information available as possible.

prevent distros from polluting other refs

---

chacra/async/__init__.py
deploy/playbooks/roles/common/handlers/main.yml
deploy/playbooks/roles/common/templates/circus.ini.j2

To further avoid dog-pilling because all workers will try to build repos and "polling" comes along and queues itself (up to ~7K items at one point).
This also fixes the issue of failing to restart celery workers

Distinct queues for polling and building repos

---

chacra/tests/test_util.py
chacra/util.py

Due to the odd way of Ceph composing repos we had to configure the app to accommodate for the same project name ('ceph') using a distinct ref ('jewel-rc') to be added to a ref ('testing') belonging to the same project name ('ceph' again).
The utility affected is used by the controller that accepts POST requests for new binaries that will also mark repos as `needs_update=True`, which will cause massive dog-pilling with the circular reference.

Fix parent projects being related to themselves 

---

chacra/controllers/binaries/__init__.py
chacra/controllers/binaries/archs.py

Read/write them by chunks using WebOb's built-in helper `FileIter`.
Fixes issue #103

Don't read large binaries at once

---

deploy/playbooks/roles/common/templates/circus.ini.j2

celery itself puts messages in the default queue so we need to make sure
there is a worker processesing those.

assign a celery worker to the default queue

---

deploy/playbooks/roles/common/handlers/main.yml
deploy/playbooks/roles/common/tasks/postgresql.yml

This is the last thing we are doing on circusctl before we fallback to just using systemd.

restart celery preventing arbitrer collisions

---

deploy/playbooks/deploy.yml
deploy/playbooks/deploy_vagrant.yml
deploy/playbooks/roles/statsd/defaults/main.yml
deploy/playbooks/roles/statsd/handlers/main.yml
deploy/playbooks/roles/statsd/tasks/main.yml
deploy/playbooks/roles/statsd/tasks/systemd.yml
deploy/playbooks/roles/statsd/templates/config/localConfig.js.j2
deploy/playbooks/roles/statsd/templates/systemd/80-statsd.preset.j2
deploy/playbooks/roles/statsd/templates/systemd/statsd.service.j2

This gets us statsd support out of the box, including systemd support.
statsd is not packaged so we are force to clone and use the release we need at time of deployment.

Statsd support

---

deploy/playbooks/roles/common/tasks/main.yml
deploy/playbooks/roles/common/templates/prod_api_creds.py.j2

This used to happen whenever the app_home directory was created as well.
That is causing an issue now because the task that creates the home directory
also sets permissions, and those will always be changed.

only reset api creds when passing api_key and api_user

---

chacra/metrics.py
chacra/tests/conftest.py
chacra/tests/test_metrics.py
deploy/playbooks/deploy.yml
deploy/playbooks/roles/common/templates/prod.py.j2

Relies on the fact that a local statsd service will be running. Requires passing the secret graphite api key every time it deploys.

Statsd client

---

chacra/tests/controllers/test_distros.py
chacra/tests/controllers/test_refs.py
requirements.txt
setup.py
tox.ini

I fixed a couple tests as well, we were missing the statsd module from #137 and the other two tests were failing with tox but passing when run with py.test directly. Comparing sets instead of unordered lists fixed that issue.
I've included flake8 tests in the tox.in but did not add them to the ``[tox]`` ``envlist`` because we have quite a few failures and I want to get the ceph-build side of the PR testing working before fixing all those.

adds a tox.ini for PR testing

---

chacra/controllers/health.py
chacra/controllers/root.py
chacra/tests/controllers/test_health.py
deploy/playbooks/roles/common/tasks/main.yml

This will be used by shaman to verify that the chacra node is healthy before giving it out at the ``/api/nodes/next/`` endpoint.

implements a /health/ endpoint

---

chacra/async/checks.py

We were returning on the first iteration of the system_checks loop in
chacra.async.checks. Derp.

ensure all system checks are used

---

chacra/tests/models/test_binaries.py

tests: fix uber granular time comparison date to skip msecs

---

chacra/controllers/repos/projects.py
chacra/models/projects.py
chacra/tests/controllers/repos/test_projects.py
chacra/tests/controllers/test_projects.py

I had forgotten to update the ProjectController for both repos and binaries so that it would list all refs followed by their sha1s. They were still show refs and then distros.

fixes a couple bugs with the sha1 addition

---

deploy/playbooks/roles/common/templates/systemd/chacra-celery.service.j2

The `celery multi` command will not log to stderr or stdout so they
can not be collected in the systemd journal. Instead use --logfile
and write all the celery workers logs into a single file.

send celery logs to a file

---

deploy/playbooks/roles/common/templates/prod.py.j2

It currently does not add ceph-release to hammer, which causes issues for dated ceph-release packages that point to old locations
See: http://tracker.ceph.com/issues/16916

ansible: include hammer ceph-release packages in ceph hammer repos

---

deploy/playbooks/roles/common/templates/prod.py.j2

We want jenkins to start the repo creation after all binaries are uploaded.

turn off automatic repo creation for ceph

---

deploy/playbooks/.gitignore
deploy/playbooks/examples/deploy_test.yml
deploy/playbooks/roles/common/defaults/main.yml
deploy/playbooks/roles/common/tasks/nginx.yml

This allows us to use self signed ssl certs with the
gitbuilder-like test chacra instances.

adds a use_self_signed_ssl option

---

deploy/playbooks/roles/common/tasks/letsencrypt.yml

ansible: renwal command should accept TOS and use the support email

---

chacra/controllers/repos/__init__.py
chacra/controllers/repos/distros.py
chacra/controllers/repos/projects.py
chacra/controllers/repos/refs.py
chacra/controllers/repos/sha1s.py
chacra/models/projects.py
chacra/tests/controllers/repos/test_distros.py
chacra/tests/controllers/repos/test_projects.py
chacra/tests/controllers/repos/test_refs.py
chacra/tests/controllers/repos/test_repos.py
chacra/tests/controllers/repos/test_sha1s.py

We need this so we can initiate repo creation with chacractl for repos
that have not already been built once.

show repos at /api/repos/ that do not have a path

---

chacra/async/__init__.py
chacra/async/recurring.py
chacra/tests/async/test_callbacks.py
chacra/tests/conftest.py

This fixes the issue where shaman would not get the requests for the various different states of a repo.
Caused by a serialization mishap using `requests` automatic one. The Repo model has a `datetime` field that would cause it to break.
Adds tests (woo hoo tests!) and try/except block in the task to capture failure and report it with logging.

Safer json encoding

---

deploy/playbooks/roles/common/tasks/nginx.yml

ansible: if letsencrypt ssl certs exist, skip asking for a new one

---

chacra/async/recurring.py

When this was in place we'd recieve a 406 back from shaman as those
endpoints return json, not plain text.

remove the Accept header in the recurring.callback task

---

requirements.txt
setup.py

This is to avoid an error we're seeing very often in the logs:
OperationalError: (psycopg2.OperationalError) SSL connection has been
closed unexpectedly
We do not see this error on chacra.ceph.com which has these versions,
but we do see it on 1.chacra.ceph.com which had 2.6.2 for psycopg2.

pin psycopg2==2.6.1 and sqlalchemy==1.0.13

---

chacra/async/recurring.py

async: if the error is not ENOENT raise, don't raise by default

---

chacra/async/checks.py
deploy/playbooks/roles/common/templates/prod.py.j2

This adds a health check that looks at the filesystem for a config defined file. If that file exists the health check will fail. This allows us to take a chacra node out of the shaman rotation without stopping services.

put chacra nodes in maintenance mode

---

chacra/async/__init__.py
chacra/metrics.py
deploy/playbooks/roles/common/templates/prod.py.j2
deploy/playbooks/roles/common/templates/prod_callbacks.py.j2

We want the``hostname`` config option so we can always be sure we are registering to shaman with the same hostname. There was an issue that required us to temporarily change the hostname on a chacra node and it incorrectly registered itself with shaman before that hostname was corrected.
We want the ``short_hostname`` config option so we can send a nice label to graphite for metrics reporting. Before this change the node ``2.chacra.ceph.com`` was using the label `2` when sending metrics to graphite, which is not very helpful in identifying where the metric originated.

adds the hostname and short_hostname config options

---

chacra/async/debian.py
chacra/async/rpm.py
chacra/models/repos.py
chacra/tests/models/test_repos.py

No need to report back on every ref because there aren't significant differences between master and say, jewel. We want metrics as granular as distro version.
Counters will also not count every binary but every repo. Counting binaries is not too useful because projects tend to have the same amount of binaries.
Repos processed is much more interesting.

more efficient metrics

---

deploy/playbooks/roles/common/templates/prod.py.j2

Without this async.post_if_healthy will register to shaman using
whatever the system hostname is, which could be incorrect.

ansible: import hostname from prod_callbacks.py into prod.py

---

chacra/async/debian.py
chacra/tests/test_util.py
chacra/util.py

This will allow us to make combined repos for older versions of ceph that are specific to a ref and sha1. Currently if we try to build an older version of jewel like 10.2.0 it's binaries get thrown out by reprepro because it finds the 10.2.3 version and ignores any older versions.

When making a deb ceph repo filter binaries by ref and sha1

---

chacra/async/__init__.py

This fixes a bug where a change in the nodes hostname results in
incorrect urls for repos reported in shaman.

use the config value for hostname when posting repo status

---

chacra/controllers/repos/__init__.py
chacra/models/repos.py
chacra/templates/repo.mako
chacra/tests/config.py
chacra/tests/controllers/repos/test_repos.py
deploy/playbooks/roles/common/templates/prod.py.j2

This endpoint can be used by clients to get the contents of
a rpm repo or deb list file for a specific repo, allowing for
clients to easily consume the repos built by chacra.
The endpoint exists at two places:
repo/$project/$ref/$sha1/$distro/$distro_version/repo/
repo/$project/$ref/$sha1/$distro/$distro_version/flavors/$flavor/repo/

repos: adds a endpoint to retrieve a deb or rpm repo file

---

chacra/controllers/repos/__init__.py

This had been defaulted to text/html which made the file
not contain newlines when viewed in a browser.

set content type to text/plain for the repo file endpoint

---

chacra/async/recurring.py
chacra/tests/async/test_recurring.py
deploy/playbooks/roles/common/templates/prod.py.j2

Allows granular configuration (in days) to keep repositories around per project/ref, falling back to the default of 14 days.
It also allows to set a minimum of repositories to keep regardless of the days configured.

configurable repositories to keep

---

deploy/playbooks/roles/common/templates/prod.py.j2

master and for-linus are also special, so keep some history around.
nightly_pre-single-major is a built-once branch used for regression
testing and should never expire.
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

ansible: purge settings for kernel branches

---

deploy/playbooks/roles/common/templates/prod.py.j2

This configuration change enables the repository creation to include the ceph-release binary when it is available.
Since the ceph-release binary is created separately we must include it when there is a new version of Ceph.  
It is cumbersome to keep updating the configuration in this way, maybe some other solution should be considered

ansible: include newer ceph-releases for ceph

---

deploy/playbooks/roles/common/tasks/letsencrypt.yml

The nginx service must be reloaded when the renewed certificate is put in
place.
Additionally, letsencrypt will only renew the certificate if it's due to
expire in <= 30 days.  Attempting to renew roughly every 15 days is
plenty.

ansible: reload nginx after renewing cert

---

deploy/playbooks/roles/common/tasks/letsencrypt.yml

nginx will still get reloaded if the certificate isn't due for renewal
yet but this will least prevent nginx from reloading if `letsencrypt`
fails for any reason.

ansible: Only reload nginx on clean `letsencrypt` exit RC

---

README.rst
chacra/tests/config.py
deploy/playbooks/roles/common/templates/prod.py.j2

These packages are not strictly "Red Hat" packages. They are published with the resources and governance of the upstream ceph.com project.
Alter the "Origin" field in the Debian repo metadata to reflect this.

set Origin to "ceph.com" in Debian repo metadata

---

chacra/tests/conftest.py

This will allow local connections from both postgresql 9.3 and 9.5 to
connect successfully. With version 9.5 if you specify a host it will
want to verify that password, but during testing we don't want that to
occur.

tests: remove host from test database connection

---

chacra/models/projects.py

As the number of binaries increase in the chacra nodes using the
relationship setup by sqlalchemy to get a project's binaries
becomes very costly. This change avoids that and only requests
the data it needs using distinct.

optimize queries in models.Project

---

deploy/playbooks/examples/deploy_prod.yml
deploy/playbooks/roles/common/defaults/main.yml
deploy/playbooks/roles/common/tasks/letsencrypt.yml
deploy/playbooks/roles/common/vars/main.yml

- chacra.ceph.com now uses a letsencrypt cert
- the && service nginx reload in the cronjob wasn't working
- letsencrypt recommends the certbot client anyway
- got rid of the unnecessary .well-known dance in letsencrypt.yml

Making some updates to letsencrypt cert maintenance

---

deploy/playbooks/roles/common/tasks/letsencrypt.yml

I believe this might have to do with nginx not being reloaded by the certbot in cron, where `service` lives in /usr/sbin/ and might not be available in `$PATH` when running in cron. Regardless, `service` is not correct anymore (even though it works)

ansible: use systemctl not service, for reloading nginx

---

chacra/async/recurring.py

Fixes issues where a 'connection' error is raised, also coming from requests. We should just catch the base `requests` exception and retry.
[2017-09-12 13:34:33,107: ERROR/Worker-1] fatal error trying to POST callback
Traceback (most recent call last):
File "/opt/chacra/src/chacra/chacra/async/recurring.py", line 200, in callback
headers=headers
File "/opt/chacra/local/lib/python2.7/site-packages/requests/api.py", line 110, in post
return request('post', url, data=data, json=json, **kwargs)
File "/opt/chacra/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/chacra/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
resp = self.send(prep, **send_kwargs)
File …

async use the base requests exception to catch retries

---

chacra/async/checks.py
chacra/tests/async/test_checks.py

This will now help get the actual error message out in logs. It wasn't being displayed before.

Error check msg should not be empty

---

deploy/playbooks/roles/common/tasks/main.yml

erlang-* packages were automatically updated this morning and caused all chacra-*
services to stop and not restart.

deploy: Remove unattended-upgrades

---

deploy/playbooks/roles/common/templates/prod.py.j2

This updates the rules so that ceph-deploy packages can go to their supported ceph versions
Anything in master should go into Luminous and newer, while older ones should use the 1.5 branch

include rules for ceph-deploy repos

---

deploy/playbooks/roles/common/tasks/main.yml

The automatic update of erlang that caused rabbitmq-server to stop is a
bug.  https://bugs.launchpad.net/ubuntu/+source/erlang/+bug/1749959
Reverting https://github.com/ceph/chacra/pull/249

deploy: Revert removal of unattended-upgrades

---

deploy/playbooks/roles/common/templates/prod.py.j2

Keep one of each to avoid confusing users who get pointed to e.g.
https://shaman.ceph.com/repos/kernel/ceph-iscsi-test with multiple
builds.
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

ansible: purge settings for iscsi kernels

---

deploy/playbooks/roles/common/templates/nginx_site.conf

ceph-debuginfo was timing out more frequently due to its size

deploy: Increase nginx proxy timeout

---

deploy/playbooks/roles/common/templates/prod.py.j2

These are missing for the main chacra instance which prevents us from creating a nautilus repo with ceph-release and ceph-deploy packages

deploy: add nautilus configs for ceph-release packages

---

chacra/async/rpm.py

This was deployed directly into prod (YOLO!) and has been working ever since.
Fixes: https://tracker.ceph.com/issues/39387

async: use --no-database to prevent repos with uninstallable (2gb) packages

---

README.rst
chacra/models/binaries.py
chacra/tests/test_util.py
chacra/util.py
config/dev.py
deploy/playbooks/roles/common/templates/prod.py.j2

Signed-off-by: Kefu Chai <kchai@redhat.com>

util,models/: include .ddeb when building deb repos

---

chacra/templates/repo.mako

On CentOS7 and earlier versions of yum, the system could use:
\$basearch
But on CentOS8, dnf (and yum) breaks. This change is backwards
compatible. There is no reason to escape the dollar character.
```
$ sudo yum -v check-update
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.0.9
cachedir: /var/cache/dnf
repo: downloading from remote: ceph
ceph packages for \x86_64                                                                                                                                                          134  B/s | 162  B     00:01    
Cannot download …
```

templates: remove escaping

---

chacra/util.py

Follow-up to https://github.com/ceph/chacra/pull/267#issuecomment-548170983
I doubt this is the right way to fix this problem but the lab is basically unable to test DEB repos at the moment

util: Ignore unknown fields

---

chacra/async/rpm.py
chacra/tests/async/test_rpm.py

On openSUSE, the repository directory structure is different to the
currently used structure. On openSUSE, we expect something like:
noarch/
repodata/
src/
x86_64/
so the repodata/ dir is on the same level than the other dirs.
This is currently not the case so fix this if the distro is set to
"opensuse".
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

async/rpm: Create repodata repo root dir for openSUSE

---

chacra/controllers/repos/__init__.py
chacra/templates/repo.mako
chacra/tests/controllers/repos/test_repos.py

On openSUSE/SLE, a repo file needs to be interpretable by zypper and
the format is slightly different to the on for yum/dnf.
So instead of creating multiple entries, just create a single one.
Fixes: https://tracker.ceph.com/issues/44183
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

controllers/repos: Create correct repo file for openSUSE/SLE

---

chacra/asynch/__init__.py
chacra/asynch/checks.py
requirements.txt
setup.py

1) update bootstrap_pecan to accept new required **kw arg
2) replace deprecated celery.task.control.inspect with
celery.app.control.Inspect
3) work around evolving interface to importlib_metadata in kombu
by effectively constraining it to 3.6.  It's complicated; see
setup.py's comment
Signed-off-by: Dan Mick <dmick@redhat.com>

Move to latest celery.  This requires a few things:

---

requirements.txt

See https://github.com/benoitc/gunicorn/issues/2741.  Basically gunicorn
breaks pecan, and I *think* it's gunicorn's fault at this point.
Signed-off-by: Dan Mick <dmick@redhat.com>

Pin gunicorn to < 20.1.0

---

deploy/playbooks/roles/common/tasks/nginx.yml

This task fails if apache2 isn't installed.

deploy: Don't make stopping apache2 fatal

---

chacra/asynch/__init__.py
chacra/asynch/checks.py
chacra/models/binaries.py
chacra/tests/async/test_checks.py

1) really fix the checks.py call for celery_has_workers() (not Inspect(), but app.control.inspect())
2) fix up disk_has_space checks: wrong config item name, popen() result not waited for, Py3 stdout/err are binary
3) force use of py-amqp rather than librabbitmq; the latter is apparently deprecated and is causing problems.
4) improve disk_has_space: check both repos_root and binary_root
5) (added late): fix binary checksum calculation for Py3.

Fix a number of issues with updating celery, bugs in disk space check

---

chacra/models/binaries.py
chacra/models/repos.py
chacra/tests/async/test_recurring.py
chacra/tests/conftest.py

This includes https://github.com/ceph/chacra/pull/291, but doesn't strictly have to.  It's inconvenient to have to have postgres running on your test machine; sqlite is lots easier to set up.  
Only a few small changes, and almost all the tests pass, but the skipped tests are ugly; not sure of a better way around it.  The problem is the sqlite driver in sqlalchemy does "if isinstance(value-to-print, datetime.datetime)" so monkeypatching datetime.datetime makes that code throw an exception.

Allow testing with sqlite

---

README.rst
chacra/controllers/repos/__init__.py
chacra/schemas/__init__.py
chacra/tests/controllers/repos/test_repos.py

Add support for "raw" repos, which are just container folders for binaries that don't need traditional repo construction.

Add 'raw' repo support

---

chacra/asynch/debian.py

This was always wrong; there was always a race between the subprocess
and the returncode check.  Something about moving to Py3 has
exposed this (perhaps the implementation had a mistaken wait, or
perhaps the new implementation is just faster.)
Anyway, since we're already using communicate(), move it to before the
returncode check, as it will wait for process completion.
Signed-off-by: Dan Mick <dmick@redhat.com>

debian.py: Make sure subprocess is complete before checking returncode

---

tox.ini

pecan uses it for running test. without adding this dependency, we'd
have following test failure:
```
>       from webtest import TestApp
E       ModuleNotFoundError: No module named 'webtest'
```
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

tox: add WebTest as a dependency of testenv

---

deploy/playbooks/roles/common/vars/main.yml

https://github.com/ionos-cloud/reprepro/issues/20#issuecomment-1110753298
I guess packaging for Ubuntu Jammy uses zstd.

deploy: Install zstd for reprepro

---

README.rst
config/dev.py
deploy/playbooks/roles/common/templates/prod.py.j2

This has been spewing errors since at least 2019.  The weird part is I can't find any mention of DDebComponents anywhere in any reprepro source tree or Google comment.  O_o  There's some indication of it being an Ubuntu invention that hasn't yet made it to mainstream (?)

Remove DDebComponents from distribution files

---

deploy/playbooks/roles/common/templates/prod.py.j2

Based on https://docs.ceph.com/en/latest/dev/release-process/#new-major-releases, this commit updates Chacra of squid's existence.

deploy/playbooks/roles/common/templates: add squid

---

chacra/asynch/recurring.py
chacra/controllers/util.py
chacra/models/__init__.py
chacra/models/binaries.py
chacra/models/repos.py

In Python 3, it's now preferred to pass the timezone to datetime.now(), as this method is deprecated.

Fix datetime.utcnow() warnings

---

chacra/controllers/repos/__init__.py
chacra/tests/async/test_callbacks.py
chacra/tests/async/test_recurring.py
chacra/tests/controllers/repos/test_repos.py
chacra/tests/controllers/test_binaries.py
chacra/tests/models/test_binaries.py
chacra/tests/models/test_repos.py
chacra/tests/test_util.py
tox.ini

The invocation of the command py.test is no longer support. That and it's supported modules have moved to pytest to avoid confusion.
- Avoid using pecan.ext for import. This isn't working according to pecan/pecan#157
- Update tox to use pytest.
- Update imports to pytest.
- Update fixtures to use preferred setup_method and teardown_method method definitions.
Fixes: #322

Update py.test to pytest

---

deploy/playbooks/roles/common/templates/prod.py.j2

The NVMEoF team requested to keep builds around longer than the default 14 days; I've modified their request but hope this will serve.  Intended to be used in place of https://github.com/ceph/chacra/pull/325

Increase retention for nvmeof branches

---

deploy/playbooks/roles/common/templates/prod.py.j2

The NVMEoF team requested to keep builds around longer than the default 14 days; I've modified their request but hope this will serve.
part2 adds another release (reef)

Increase retention for nvmeof branches (part 2)
